export default {
  login: "sindrimt",
  id: 69514093,
  node_id: "MDQ6VXNlcjY5NTE0MDkz",
  avatar_url: "https://avatars.githubusercontent.com/u/69514093?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/sindrimt",
  html_url: "https://github.com/sindrimt",
  followers_url: "https://api.github.com/users/sindrimt/followers",
  following_url: "https://api.github.com/users/sindrimt/following{/other_user}",
  gists_url: "https://api.github.com/users/sindrimt/gists{/gist_id}",
  starred_url: "https://api.github.com/users/sindrimt/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/sindrimt/subscriptions",
  organizations_url: "https://api.github.com/users/sindrimt/orgs",
  repos_url: "https://api.github.com/users/sindrimt/repos",
  events_url: "https://api.github.com/users/sindrimt/events{/privacy}",
  received_events_url: "https://api.github.com/users/sindrimt/received_events",
  type: "User",
  site_admin: false,
  name: "Sindrimt",
  company: "O'Burger",
  blog: "https://oburger.xyz/",
  location: "Norway",
  email: "Sindrimt@gmail.com",
  hireable: null,
  bio: "Proud owner of oburger.xyz\r\n",
  twitter_username: null,
  public_repos: 89,
  public_gists: 55,
  followers: 7653,
  following: 42,
  created_at: "2020-08-11T11:59:38Z",
  updated_at: "2021-08-27T18:32:56Z",
};
